import { NextRequest, NextResponse } from "next/server";
import { readFileSync, writeFileSync, mkdirSync } from "fs";
import { join } from "path";
import { execFile } from "child_process";
import { writeFile, unlink, mkdir } from "fs/promises";
import { tmpdir } from "os";
import { bigquery, DATASET } from "@/lib/bigquery";

/**
 * Stramark — Payment Verification API (3-Layer)
 *
 * Confirmations stored in BigQuery (persistent across deploys).
 * Verification data (items, anomalies) in JSON file (cache, regenerated by sync).
 *
 * GET  /api/stramark/eushipments/payment-verification
 * POST /api/stramark/eushipments/payment-verification
 */

export const dynamic = "force-dynamic";

const POS_API_BASE = process.env.POSCAKE_API_URL || "https://pos.pages.fm/api/v1";
const POS_API_KEY = process.env.POSCAKE_API_KEY || "";
const POS_SHOP_ID = process.env.POSCAKE_SHOP_ID || "1635307570";

const PROPOSALS_PATH = join(process.cwd(), "..", "data", "stramark", "payment_verification_proposals.json");
const ALLOWED_APPROVERS = ["Trà My", "Grace Kim"];
const BQ_TABLE = `${DATASET}.payout_protocols`;

// ── BQ helpers for confirmations ──

async function loadConfirmationsFromBQ(): Promise<Record<string, any>> {
    try {
        const [rows] = await bigquery.query({
            query: `SELECT protocol_number, client_id, verification_status,
                confirmed_by_1, confirmed_at_1, transaction_id_1,
                confirmed_by_2, confirmed_at_2, transaction_id_2,
                disputed_by, dispute_reason, pos_check_status, pos_updated_at
            FROM \`${BQ_TABLE}\``,
        });
        const map: Record<string, any> = {};
        for (const r of rows) {
            const key = `${r.protocol_number}_${r.client_id || ""}`;
            map[key] = r;
        }
        return map;
    } catch (e) {
        console.error("BQ loadConfirmations error:", e);
        return {};
    }
}

async function saveConfirmationToBQ(protocolNumber: string, clientId: string | null, fields: Record<string, any>): Promise<void> {
    const setClauses = Object.entries(fields)
        .filter(([, v]) => v !== undefined)
        .map(([k, v]) => {
            if (v === null) return `${k} = NULL`;
            if (typeof v === "string") return `${k} = '${v.replace(/'/g, "\\'")}'`;
            return `${k} = ${v}`;
        })
        .join(", ");

    const query = `UPDATE \`${BQ_TABLE}\` SET ${setClauses}, synced_at = CURRENT_TIMESTAMP()
        WHERE protocol_number = '${protocolNumber}'
        ${clientId ? `AND client_id = '${clientId}'` : ""}`;

    try {
        await bigquery.query({ query });
    } catch (e) {
        console.error("BQ saveConfirmation error:", e);
        throw e;
    }
}

// ── Proposals file I/O (verification cache only) ──

interface Protocol {
    protocol_number: string;
    client_id: string | null;
    protocol_date: string | null;
    source_filename: string;
    uploaded_at: string;
    awb_count: number;
    total_amount_ron: number;
    paid_eur: number | null;
    matched_count: number;
    anomaly_count: number;
    anomalies: any[];
    items: any[];
    missing_from_protokol: any[];
    verification_status: "pending" | "verified" | "anomaly" | "confirmed" | "disputed";
    confirmed_by_1: string | null;
    confirmed_at_1: string | null;
    confirmed_by_2: string | null;
    confirmed_at_2: string | null;
    disputed_by?: string;
    dispute_reason?: string;
    transaction_id?: string;
    transaction_id_1?: string;
    transaction_id_2?: string;
    pos_check?: any;
    pos_updated_at?: string;
    pos_update_results?: any;
}

interface ProposalsFile {
    protocols: Protocol[];
    invoices?: any[];
    compensations?: any[];
    cod_cross_check?: any;
}

function loadProposals(): ProposalsFile {
    try {
        const raw = readFileSync(PROPOSALS_PATH, "utf-8");
        return JSON.parse(raw);
    } catch {
        return { protocols: [] };
    }
}

function saveProposals(data: ProposalsFile): void {
    try {
        mkdirSync(join(process.cwd(), "..", "data", "stramark"), { recursive: true });
        writeFileSync(PROPOSALS_PATH, JSON.stringify(data, null, 2), "utf-8");
    } catch (e) {
        console.error("Failed to save proposals:", e);
    }
}

/** Merge BQ confirmations into JSON protocols (BQ is source of truth for approvals) */
function mergeConfirmations(protocols: Protocol[], bqData: Record<string, any>): Protocol[] {
    for (const p of protocols) {
        const key = `${p.protocol_number}_${p.client_id || ""}`;
        const bq = bqData[key];
        if (!bq) continue;

        // BQ overrides JSON for confirmation fields
        if (bq.confirmed_by_1) p.confirmed_by_1 = bq.confirmed_by_1;
        if (bq.confirmed_at_1) p.confirmed_at_1 = typeof bq.confirmed_at_1 === "object" ? bq.confirmed_at_1.value : bq.confirmed_at_1;
        if (bq.transaction_id_1) p.transaction_id_1 = bq.transaction_id_1;
        if (bq.confirmed_by_2) p.confirmed_by_2 = bq.confirmed_by_2;
        if (bq.confirmed_at_2) p.confirmed_at_2 = typeof bq.confirmed_at_2 === "object" ? bq.confirmed_at_2.value : bq.confirmed_at_2;
        if (bq.transaction_id_2) p.transaction_id_2 = bq.transaction_id_2;
        if (bq.disputed_by) p.disputed_by = bq.disputed_by;
        if (bq.dispute_reason) p.dispute_reason = bq.dispute_reason;
        if (bq.pos_updated_at) p.pos_updated_at = typeof bq.pos_updated_at === "object" ? bq.pos_updated_at.value : bq.pos_updated_at;

        // BQ status overrides JSON status if BQ has confirmation
        if (bq.verification_status === "confirmed" || bq.verification_status === "disputed") {
            p.verification_status = bq.verification_status;
        }
    }
    return protocols;
}

// ── POS API helpers ──

async function fetchPosOrderStatus(orderId: string): Promise<string | null> {
    try {
        const resp = await fetch(
            `${POS_API_BASE}/shops/${POS_SHOP_ID}/orders/${orderId}?api_key=${POS_API_KEY}`,
            { signal: AbortSignal.timeout(15000) }
        );
        if (!resp.ok) return null;
        const data = await resp.json();
        const order = data.data || data;
        return (order.status_name || "").toLowerCase().trim() || null;
    } catch {
        return null;
    }
}

async function updatePosStatus(orderId: string, newStatus: string): Promise<boolean> {
    // POS Cake requires numeric status codes, not string names
    const STATUS_CODES: Record<string, number> = {
        received_money: 15,
        delivered: 3,
        returning: 12,
        returned: 13,
    };
    const statusCode = STATUS_CODES[newStatus] || newStatus;
    try {
        const resp = await fetch(
            `${POS_API_BASE}/shops/${POS_SHOP_ID}/orders/${orderId}?api_key=${POS_API_KEY}`,
            {
                method: "PUT",
                headers: { "Content-Type": "application/json" },
                body: JSON.stringify({ status: statusCode }),
                signal: AbortSignal.timeout(10000),
            }
        );
        return resp.ok;
    } catch {
        return false;
    }
}

// ── GET: Return protocols ──

export async function GET() {
    const data = loadProposals();

    // Merge BQ confirmations (source of truth) into JSON verification data
    const bqData = await loadConfirmationsFromBQ();
    mergeConfirmations(data.protocols, bqData);

    const pending = data.protocols.filter(
        p => p.verification_status === "pending" || p.verification_status === "verified" || p.verification_status === "anomaly"
    );

    return NextResponse.json({
        protocols: data.protocols,
        pendingCount: pending.length,
        invoices: data.invoices || [],
        codCrossCheck: data.cod_cross_check || null,
        posStatusCheck: (data as any).pos_status_check || null,
    });
}

// ── POST: Handle actions ──

export async function POST(req: NextRequest) {
    const contentType = req.headers.get("content-type") || "";

    // Handle file upload (multipart/form-data)
    if (contentType.includes("multipart/form-data")) {
        return handleUpload(req);
    }

    // Handle JSON actions
    const body = await req.json();
    const { action } = body;

    if (action === "sync-email") {
        return handleSyncEmail();
    }
    if (action === "resync-payout") {
        return handleResyncPayout();
    }
    if (action === "confirm") {
        return handleConfirm(body);
    }
    if (action === "check-pos-status") {
        return handleCheckPosStatus();
    }
    if (action === "update-pos") {
        return handleUpdatePos(body);
    }
    if (action === "dispute") {
        return handleDispute(body);
    }

    return NextResponse.json({ error: "Unknown action" }, { status: 400 });
}

// ── Resync Payout Data (eu_shipment_sync + re-verify) ──

async function handleResyncPayout(): Promise<NextResponse> {
    const syncScript = join(process.cwd(), "..", "sync", "stramark", "eu_shipment_sync.py");
    const emailScript = join(process.cwd(), "..", "sync", "stramark", "protokol_email_sync.py");
    const python = process.platform === "win32" ? "python" : "python3";
    const cwd = join(process.cwd(), "..");

    return new Promise<NextResponse>((resolve) => {
        // Step 1: Resync payout data from euShipments API
        execFile(python, [syncScript, "--resync-all"], { timeout: 600000, cwd }, (err1, stdout1, stderr1) => {
            if (err1) {
                resolve(NextResponse.json({
                    success: false,
                    error: `EU Shipment sync failed: ${stderr1?.slice(-300) || err1.message}`,
                }, { status: 500 }));
                return;
            }

            // Step 2: Re-verify protocols with fresh payout data
            execFile(python, [emailScript, "--reprocess", "--days", "30", "--skip-discord"], { timeout: 300000, cwd }, (err2, stdout2, stderr2) => {
                if (err2) {
                    resolve(NextResponse.json({
                        success: true,
                        message: "Payout synced but re-verify failed. Reload to see updated data.",
                        error: stderr2?.slice(-300) || err2.message,
                    }));
                    return;
                }

                const data = loadProposals();
                const matched = data.protocols.filter(p => p.anomaly_count === 0).length;
                const anomaly = data.protocols.filter(p => p.anomaly_count > 0).length;

                resolve(NextResponse.json({
                    success: true,
                    message: `Resync complete: ${data.protocols.length} protocols, ${matched} verified, ${anomaly} with anomalies`,
                }));
            });
        });
    });
}

// ── Sync from Email ──

async function handleSyncEmail(): Promise<NextResponse> {
    const scriptPath = join(process.cwd(), "..", "sync", "stramark", "protokol_email_sync.py");

    return new Promise<NextResponse>((resolve) => {
        execFile(
            process.platform === "win32" ? "python" : "python3",
            [scriptPath, "--json-output"],
            { timeout: 180000, cwd: join(process.cwd(), "..") },
            (err, stdout, stderr) => {
                if (err) {
                    console.error("Email sync error:", stderr);
                    resolve(NextResponse.json({
                        success: false,
                        error: stderr?.slice(-500) || err.message,
                    }, { status: 500 }));
                    return;
                }

                // Reload proposals after sync
                const data = loadProposals();
                const pending = data.protocols.filter(
                    p => p.verification_status !== "confirmed" && p.verification_status !== "disputed"
                );

                // Parse JSON output from script (last line)
                let syncResult = null;
                try {
                    const lines = stdout.trim().split("\n");
                    const lastLine = lines[lines.length - 1];
                    syncResult = JSON.parse(lastLine);
                } catch { /* ignore */ }

                resolve(NextResponse.json({
                    success: true,
                    result: syncResult,
                    pendingCount: pending.length,
                }));
            }
        );
    });
}

// ── Upload Protokol (legacy) ──

async function handleUpload(req: NextRequest): Promise<NextResponse> {
    try {
        const formData = await req.formData();
        const file = formData.get("file") as File | null;

        if (!file) {
            return NextResponse.json({ error: "No file provided" }, { status: 400 });
        }

        if (!file.name.toLowerCase().endsWith(".xlsx")) {
            return NextResponse.json({ error: "Only .xlsx files accepted" }, { status: 400 });
        }

        // Write to temp file
        const tmpDir = join(tmpdir(), "stramark_protokol");
        await mkdir(tmpDir, { recursive: true });
        const tmpPath = join(tmpDir, file.name);
        const bytes = await file.arrayBuffer();
        await writeFile(tmpPath, Buffer.from(bytes));

        // Execute Python verification script
        const scriptPath = join(process.cwd(), "..", "sync", "stramark", "payment_verification.py");

        return new Promise<NextResponse>((resolve) => {
            execFile(
                process.platform === "win32" ? "python" : "python3",
                [scriptPath, "--file", tmpPath, "--json-output"],
                { timeout: 120000, cwd: join(process.cwd(), "..") },
                async (err, stdout, stderr) => {
                    // Clean up temp file
                    try { await unlink(tmpPath); } catch { /* ignore */ }

                    if (err) {
                        console.error("Verification script error:", stderr);
                        resolve(NextResponse.json({
                            success: false,
                            error: stderr?.slice(-500) || err.message,
                        }, { status: 500 }));
                        return;
                    }

                    // Reload proposals after script execution
                    const data = loadProposals();
                    const pending = data.protocols.filter(
                        p => p.verification_status !== "confirmed" && p.verification_status !== "disputed"
                    );

                    // Parse JSON output from script (last line)
                    let scriptResult = null;
                    try {
                        const lines = stdout.trim().split("\n");
                        const lastLine = lines[lines.length - 1];
                        scriptResult = JSON.parse(lastLine);
                    } catch { /* ignore */ }

                    resolve(NextResponse.json({
                        success: true,
                        result: scriptResult,
                        pendingCount: pending.length,
                        output: stderr?.slice(-300),
                    }));
                }
            );
        });
    } catch (e: any) {
        return NextResponse.json({ error: e.message }, { status: 500 });
    }
}

// ── Confirm Protocol ──

async function handleConfirm(body: any): Promise<NextResponse> {
    const { protocolNumber, confirmer, transactionId } = body;

    if (!protocolNumber || !confirmer) {
        return NextResponse.json({ error: "Missing protocolNumber or confirmer" }, { status: 400 });
    }

    if (!ALLOWED_APPROVERS.includes(confirmer)) {
        return NextResponse.json(
            { error: `Confirmer must be one of: ${ALLOWED_APPROVERS.join(", ")}` },
            { status: 403 }
        );
    }

    const data = loadProposals();
    const protocol = data.protocols.find((p: any) => p.protocol_number === protocolNumber);

    if (!protocol) {
        return NextResponse.json({ error: "Protocol not found" }, { status: 404 });
    }

    if (protocol.verification_status === "confirmed") {
        return NextResponse.json({ error: "Already confirmed" }, { status: 400 });
    }
    if (protocol.verification_status === "disputed") {
        return NextResponse.json({ error: "Protocol is disputed" }, { status: 400 });
    }

    const now = new Date().toISOString();

    // Load BQ confirmations to get current state (source of truth)
    const bqData = await loadConfirmationsFromBQ();
    const bqKey = `${protocolNumber}_${protocol.client_id || ""}`;
    const bqProto = bqData[bqKey] || {};

    // Use BQ state if available
    const currentConfirmer1 = bqProto.confirmed_by_1 || protocol.confirmed_by_1;

    if (!currentConfirmer1) {
        // First confirmation → save to BQ
        await saveConfirmationToBQ(protocolNumber, protocol.client_id, {
            confirmed_by_1: confirmer,
            confirmed_at_1: now,
            transaction_id_1: transactionId || null,
        });

        // Also update JSON cache
        protocol.confirmed_by_1 = confirmer;
        protocol.confirmed_at_1 = now;
        if (transactionId) protocol.transaction_id_1 = transactionId;
        saveProposals(data);

        return NextResponse.json({
            success: true,
            message: `First confirmation by ${confirmer}. Waiting for second approver.`,
            confirmations: 1,
        });
    }

    if (currentConfirmer1 === confirmer) {
        return NextResponse.json(
            { error: "Same person cannot provide both confirmations" },
            { status: 400 }
        );
    }

    // Second confirmation → save to BQ
    await saveConfirmationToBQ(protocolNumber, protocol.client_id, {
        confirmed_by_2: confirmer,
        confirmed_at_2: now,
        transaction_id_2: transactionId || null,
        verification_status: "confirmed",
    });

    // Update JSON cache
    protocol.confirmed_by_2 = confirmer;
    protocol.confirmed_at_2 = now;
    if (transactionId) protocol.transaction_id_2 = transactionId;
    protocol.verification_status = "confirmed";

    // Cross-check POS status — propose updates, don't auto-update
    const posCheckResults: any[] = [];
    const matchedItems = (protocol.items || []).filter(
        (item: any) => item.match_status === "matched" && item.pos_order_id
    );

    const toCheck = matchedItems;
    for (const item of toCheck) {
        const orderId = item.pos_order_id;
        const liveStatus = await fetchPosOrderStatus(orderId);
        posCheckResults.push({
            orderId,
            currentStatus: liveStatus || "unknown",
            needsUpdate: liveStatus === "delivered",
        });
        await new Promise(r => setTimeout(r, 300));
    }

    const needsUpdate = posCheckResults.filter(r => r.needsUpdate).length;
    const alreadyCollected = posCheckResults.filter(r => r.currentStatus === "received_money").length;

    protocol.pos_check = {
        checked: toCheck.length,
        total: matchedItems.length,
        needs_update: needsUpdate,
        already_collected: alreadyCollected,
        details: posCheckResults,
    };

    // Save POS check status to BQ
    await saveConfirmationToBQ(protocolNumber, protocol.client_id, {
        pos_check_status: needsUpdate > 0 ? "needs_update" : "all_collected",
    }).catch(() => {});

    saveProposals(data);

    return NextResponse.json({
        success: true,
        message: `Confirmed by ${currentConfirmer1} + ${confirmer}`,
        confirmations: 2,
        posCheck: protocol.pos_check,
    });
}

// ── Check POS Status for all paid protocols ──

async function handleCheckPosStatus(): Promise<NextResponse> {
    const data = loadProposals();
    const confirmedProtocols = data.protocols.filter(
        (p: Protocol) => p.verification_status === "confirmed"
    );

    const results: any[] = [];
    const orderIds = new Set<string>();

    // Collect all matched order IDs from confirmed protocols
    for (const proto of confirmedProtocols) {
        for (const item of (proto.items || [])) {
            if (item.match_status === "matched" && item.pos_order_id) {
                orderIds.add(item.pos_order_id);
            }
        }
    }

    // Check POS status for each order (sample first 50)
    const idsToCheck = Array.from(orderIds).slice(0, 50);
    let needsUpdate = 0;
    let alreadyCollected = 0;

    for (const orderId of idsToCheck) {
        const liveStatus = await fetchPosOrderStatus(orderId);
        const needs = liveStatus === "delivered";
        if (needs) needsUpdate++;
        if (liveStatus === "received_money") alreadyCollected++;
        results.push({ orderId, currentStatus: liveStatus || "unknown", needsUpdate: needs });
        await new Promise(r => setTimeout(r, 200));
    }

    // Save check results
    (data as any).pos_status_check = {
        checked_at: new Date().toISOString(),
        total_orders: orderIds.size,
        checked: idsToCheck.length,
        needs_update: needsUpdate,
        already_collected: alreadyCollected,
        orders: results,
    };
    saveProposals(data);

    return NextResponse.json({
        success: true,
        posStatusCheck: (data as any).pos_status_check,
    });
}

// ── Update POS Status (separate action after confirmation) ──

async function handleUpdatePos(body: any): Promise<NextResponse> {
    const { protocolNumber, orderIds } = body;

    // Determine which orders to update
    let idsToUpdate: string[] = [];

    if (orderIds && Array.isArray(orderIds)) {
        // Direct order IDs from POS status check
        idsToUpdate = orderIds;
    } else if (protocolNumber) {
        // From protocol confirmation
        const data = loadProposals();
        const protocol = data.protocols.find((p: any) => p.protocol_number === protocolNumber);
        if (!protocol) {
            return NextResponse.json({ error: "Protocol not found" }, { status: 404 });
        }
        if (protocol.verification_status !== "confirmed") {
            return NextResponse.json({ error: "Protocol must be confirmed (2/2) first" }, { status: 400 });
        }
        idsToUpdate = (protocol.items || [])
            .filter((item: any) => item.match_status === "matched" && item.pos_order_id)
            .map((item: any) => item.pos_order_id);
    } else {
        return NextResponse.json({ error: "Missing protocolNumber or orderIds" }, { status: 400 });
    }

    const posResults: any[] = [];
    for (const orderId of idsToUpdate) {
        const liveStatus = await fetchPosOrderStatus(orderId);

        if (!liveStatus) {
            posResults.push({ orderId, result: "skip", reason: "Cannot fetch status" });
            continue;
        }
        if (liveStatus === "received_money") {
            posResults.push({ orderId, result: "skip", reason: "Already received_money" });
            continue;
        }
        if (liveStatus !== "delivered") {
            posResults.push({ orderId, result: "skip", reason: `Status: ${liveStatus}` });
            continue;
        }

        const ok = await updatePosStatus(orderId, "received_money");
        posResults.push({ orderId, result: ok ? "updated" : "failed" });
        await new Promise(r => setTimeout(r, 500));
    }

    const updated = posResults.filter(r => r.result === "updated").length;
    const skipped = posResults.filter(r => r.result === "skip").length;
    const failed = posResults.filter(r => r.result === "failed").length;

    // Save results to BQ + JSON cache
    const data = loadProposals();
    if (protocolNumber) {
        const protocol = data.protocols.find((p: any) => p.protocol_number === protocolNumber);
        if (protocol) {
            protocol.pos_updated_at = new Date().toISOString();
            protocol.pos_update_results = { updated, skipped, failed, total: idsToUpdate.length };

            // Save to BQ
            await saveConfirmationToBQ(protocolNumber, protocol.client_id, {
                pos_updated_at: protocol.pos_updated_at,
                pos_check_status: "updated",
            }).catch(() => {});
        }
    }
    if ((data as any).pos_status_check) {
        (data as any).pos_status_check.last_update_at = new Date().toISOString();
        (data as any).pos_status_check.last_update_results = { updated, skipped, failed };
    }
    saveProposals(data);

    return NextResponse.json({
        success: true,
        message: `POS updated: ${updated} orders → received_money`,
        posUpdates: { updated, skipped, failed, total: idsToUpdate.length },
    });
}

// ── Dispute Protocol ──

async function handleDispute(body: any): Promise<NextResponse> {
    const { protocolNumber, disputedBy, reason } = body;

    if (!protocolNumber || !disputedBy) {
        return NextResponse.json({ error: "Missing protocolNumber or disputedBy" }, { status: 400 });
    }

    const data = loadProposals();
    const protocol = data.protocols.find(p => p.protocol_number === protocolNumber);

    if (!protocol) {
        return NextResponse.json({ error: "Protocol not found" }, { status: 404 });
    }

    // Save to BQ (source of truth)
    await saveConfirmationToBQ(protocolNumber, protocol.client_id, {
        verification_status: "disputed",
        disputed_by: disputedBy,
        dispute_reason: reason || "",
    });

    // Update JSON cache
    protocol.verification_status = "disputed";
    protocol.disputed_by = disputedBy;
    protocol.dispute_reason = reason || "";
    saveProposals(data);

    return NextResponse.json({
        success: true,
        message: `Protocol disputed by ${disputedBy}`,
    });
}
