"""
TCE PDF Parser — Extract per-order fulfillment costs from TCE Deviz PDF files.

Parses Deviz_*.pdf files generated by TCE Holding and extracts individual
shipment records with cost, filtering only Stramark ("Aurelia Wear") orders.

Created: 2026-03-06
"""
import re
import logging
from pathlib import Path
from datetime import datetime

logger = logging.getLogger(__name__)

# ═══ Business Rules ═══

# Only orders with this name in Expeditor or Destinatar belong to Stramark
STRAMARK_IDENTIFIER = "Aurelia Wear"

# Names to explicitly EXCLUDE (other teams sharing the same TCE account)
EXCLUDED_NAMES = [
    "sorina", "sophia", "xophia", "oddiehouse", "oddie house", "oddie"
]

# TCE VAT rate (confirmed: Deviz prices EXCLUDE VAT)
TCE_VAT_RATE = 0.21


# ═══ PDF Parsing ═══

def parse_deviz_pdf(filepath):
    """Parse a TCE Deviz PDF file and extract all shipment rows.

    Args:
        filepath: Path to Deviz_*.pdf file

    Returns:
        List of dicts with keys:
            id, date, expeditor_name, expeditor_location,
            destinatar_name, destinatar_location, packages, weight,
            price, currency, raw_line
    """
    try:
        import pdfplumber
    except ImportError:
        logger.error("pdfplumber not installed. Run: pip install pdfplumber")
        return []

    filepath = Path(filepath)
    if not filepath.exists():
        logger.error(f"File not found: {filepath}")
        return []

    rows = []
    deviz_id = None

    try:
        with pdfplumber.open(filepath) as pdf:
            full_text = ""
            for page in pdf.pages:
                text = page.extract_text()
                if text:
                    full_text += text + "\n"

            # Extract Deviz ID from header
            deviz_match = re.search(r'ID:\s*(\d+)', full_text)
            if deviz_match:
                deviz_id = deviz_match.group(1)

            # Extract date range from header
            date_range = None
            date_range_match = re.search(
                r'(\d{4}-\d{2}-\d{2})\s*[–-]\s*(\d{4}-\d{2}-\d{2})', full_text
            )
            if date_range_match:
                date_range = (date_range_match.group(1), date_range_match.group(2))

            # Parse rows: each row starts with a 7-digit ID and date
            # Format: ID Date Expeditor(Name Country Region City) Destinatar(Name Country Region City) Packages Weight Price Currency
            lines = full_text.split("\n")

            for line in lines:
                row = _parse_deviz_line(line)
                if row:
                    row["deviz_id"] = deviz_id
                    rows.append(row)

    except Exception as e:
        logger.error(f"Error parsing {filepath.name}: {e}")

    logger.info(f"  Parsed {filepath.name}: {len(rows)} rows (Deviz ID: {deviz_id})")
    return rows


def _parse_deviz_line(line):
    """Parse a single line from Deviz PDF text extraction.

    Expected format (from pdfplumber text extraction):
    2099499 2026-02-23 Aurelia Wear România București București Mirela Hauca România Suceava Siret 1 1 5.32 EUR

    The challenge: Expeditor and Destinatar each have 4 fields (Name, Country, Region, City)
    and names can contain spaces. We rely on "România" as country delimiter.
    """
    line = line.strip()
    if not line:
        return None

    # Must start with a 7-digit ID
    match = re.match(r'^(\d{7})\s+(\d{4}-\d{2}-\d{2})\s+(.+)$', line)
    if not match:
        return None

    shipment_id = match.group(1)
    date_str = match.group(2)
    remainder = match.group(3)

    # Extract price and currency from the end
    # Pattern: ... number number price currency
    # End of line: "1 1 5.32 EUR" (packages, kg, price, currency)
    price_match = re.search(
        r'\s+(\d+)\s+(\d+)\s+(\d+(?:\.\d+)?)\s+(EUR|RON|BGN)\s*$', remainder
    )
    if not price_match:
        return None

    packages = int(price_match.group(1))
    weight = int(price_match.group(2))
    price = float(price_match.group(3))
    currency = price_match.group(4)

    # Get the name/address portion (everything before packages/weight/price)
    name_section = remainder[:price_match.start()].strip()

    # Split into Expeditor and Destinatar using "România" occurrences
    # Pattern: ExpName România ExpRegion ExpCity DestName România DestRegion DestCity
    # There are exactly 2 "România" in a normal row (Expeditor country and Destinatar country)
    romania_positions = [m.start() for m in re.finditer(r'România', name_section)]

    if len(romania_positions) >= 2:
        # First România ends Expeditor name, second starts Destinatar address
        exp_name = name_section[:romania_positions[0]].strip()

        # Between first România and just before second România is:
        # ExpRegion ExpCity DestName
        middle = name_section[romania_positions[0] + len("România"):romania_positions[1]].strip()

        # Destinatar address after second România
        dest_after_romania = name_section[romania_positions[1] + len("România"):].strip()

        # Middle section: "ExpRegion ExpCity DestName"
        # Split by detecting where ExpCity ends and DestName begins
        # This is tricky because both can contain spaces
        # Heuristic: ExpRegion and ExpCity are typically single words or with hyphen
        # Try splitting middle into 2 parts for region/city + rest as dest name
        middle_parts = middle.split()
        if len(middle_parts) >= 3:
            # First 2 parts: Region, City of Expeditor
            # Rest: Name of Destinatar
            exp_region = middle_parts[0]
            exp_city = middle_parts[1]
            dest_name = " ".join(middle_parts[2:])
        elif len(middle_parts) == 2:
            exp_region = middle_parts[0]
            exp_city = middle_parts[1]
            dest_name = ""
        else:
            exp_region = middle_parts[0] if middle_parts else ""
            exp_city = ""
            dest_name = ""

        # Destinatar location from after second România
        dest_parts = dest_after_romania.split()
        dest_region = dest_parts[0] if len(dest_parts) >= 1 else ""
        # City may be truncated with "..."
        dest_city = " ".join(dest_parts[1:]) if len(dest_parts) >= 2 else ""

    elif len(romania_positions) == 1:
        # Unusual case - only one România found
        exp_name = name_section[:romania_positions[0]].strip()
        dest_name = name_section[romania_positions[0] + len("România"):].strip()
        exp_region = exp_city = dest_region = dest_city = ""
    else:
        # No România found - can't parse reliably
        return None

    try:
        parsed_date = datetime.strptime(date_str, "%Y-%m-%d")
    except ValueError:
        parsed_date = None

    return {
        "id": shipment_id,
        "date": date_str,
        "parsed_date": parsed_date,
        "expeditor_name": exp_name,
        "expeditor_region": exp_region,
        "expeditor_city": exp_city,
        "destinatar_name": dest_name,
        "destinatar_region": dest_region,
        "destinatar_city": dest_city,
        "packages": packages,
        "weight": weight,
        "price": price,
        "currency": currency,
        "raw_line": line[:200],
    }


# ═══ Filtering ═══

def _is_stramark_name(name):
    """Check if a name matches Stramark identifier (Aurelia Wear)."""
    if not name:
        return False
    return STRAMARK_IDENTIFIER.lower() in name.lower()


def _is_excluded_name(name):
    """Check if name belongs to an excluded team."""
    if not name:
        return False
    name_lower = name.lower().strip()
    return any(excl in name_lower for excl in EXCLUDED_NAMES)


def filter_stramark_orders(rows):
    """Filter rows to keep only Stramark (Aurelia Wear) orders.

    Business rules:
    - Forward: Expeditor is "Aurelia Wear"
    - Return:  Destinatar is "Aurelia Wear"
    - Exclude: Sorina, Sophia, Oddiehouse (other teams)

    Returns:
        List of filtered rows with added 'is_return' boolean
    """
    filtered = []
    excluded_count = 0
    other_team_count = 0

    for row in rows:
        exp_name = row.get("expeditor_name", "")
        dest_name = row.get("destinatar_name", "")

        is_forward = _is_stramark_name(exp_name)
        is_return = _is_stramark_name(dest_name) and not is_forward

        if is_forward or is_return:
            # Double-check: exclude if the OTHER party is also excluded
            other_name = dest_name if is_forward else exp_name
            if _is_excluded_name(other_name):
                excluded_count += 1
                continue

            row["is_return"] = is_return
            filtered.append(row)
        else:
            # Check if it's a known excluded team order
            if _is_excluded_name(exp_name) or _is_excluded_name(dest_name):
                other_team_count += 1
            # else: order from another team entirely, skip silently

    if excluded_count > 0:
        logger.info(f"  Excluded {excluded_count} orders (matched both Stramark and excluded names)")
    if other_team_count > 0:
        logger.debug(f"  Skipped {other_team_count} orders from other teams")

    return filtered


# ═══ Schema Normalization ═══

def normalize_to_ffm_schema(filtered_rows):
    """Convert filtered PDF rows to ffm_shipments schema records.

    Applies:
    - VAT: price_incl_vat = price * (1 + 0.21)
    - Partner tag: ffm_partner = "TCE"
    - Sync source: sync_source = "pdf"
    - For forward orders: pos_order_id = AWB (TCE ID = POS tracking code)
    - For return orders: pos_order_id = None (cannot map directly), original_order_id = None

    Returns:
        Tuple of (records, unmatched_returns_info)
        where unmatched_returns_info = {"count": int, "total_cost_eur": float}
    """
    records = []
    unmatched_returns = {"count": 0, "total_cost_excl_vat": 0.0, "total_cost_incl_vat": 0.0}

    for row in filtered_rows:
        price_excl = row["price"]
        price_incl = round(price_excl * (1 + TCE_VAT_RATE), 4)
        is_return = row.get("is_return", False)

        # For forward orders, the TCE ID is the same as POS tracking code
        # For return orders, TCE creates a new AWB → cannot map to POS order directly
        if is_return:
            pos_order_id = None
            unmatched_returns["count"] += 1
            unmatched_returns["total_cost_excl_vat"] += price_excl
            unmatched_returns["total_cost_incl_vat"] += price_incl
        else:
            pos_order_id = str(row["id"])

        record = {
            "awb": str(row["id"]),
            "ref_number": str(row["id"]),
            "pos_order_id": pos_order_id,
            "ffm_partner": "TCE",
            "client_id": "77795525",
            "status": "Delivered" if not is_return else "Returned",
            "price_excl_vat": price_excl,
            "price_incl_vat": price_incl,
            "vat_rate": TCE_VAT_RATE,
            "currency": row.get("currency", "EUR"),
            "is_return_shipment": is_return,
            "original_order_id": None,  # Cannot map returns to original POS orders
            "cod_amount": None,
            "created_date": row["parsed_date"].isoformat() if row.get("parsed_date") else None,
            "delivered_date": row["parsed_date"].isoformat() if row.get("parsed_date") and not is_return else None,
            "returned_date": row["parsed_date"].isoformat() if row.get("parsed_date") and is_return else None,
            "raw_response": row.get("raw_line", ""),
            "sync_source": "pdf",
        }
        records.append(record)

    # Round totals
    unmatched_returns["total_cost_excl_vat"] = round(unmatched_returns["total_cost_excl_vat"], 2)
    unmatched_returns["total_cost_incl_vat"] = round(unmatched_returns["total_cost_incl_vat"], 2)

    return records, unmatched_returns
